name: Build ayugram-desktop (AUR)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Build pkg
        run: |
          docker run --rm -v $(pwd):/share archlinux:latest bash -euxc '
            pacman-key --init
            pacman-key --populate archlinux
            pacman -Syu --noconfirm
            pacman -Sy --needed --noconfirm base-devel git sudo curl jq vulkan-headers openssl ca-certificates

            useradd -m builder
            echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder
            chmod 0440 /etc/sudoers.d/builder

            git config --global http.sslBackend "openssl"

            AUR_URL="https://aur.archlinux.org/rpc/?v=5&type=info&arg=ayugram-desktop"
            VER=$(curl -s "$AUR_URL" | jq -r ".results[0].Version")
            echo "AUR_VERSION=$VER" >> /share/versioninfo

            LATEST_TAG=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
            echo "LATEST_TAG=$LATEST_TAG" >> /share/versioninfo

            if [ "$LATEST_TAG" = "v$VER" ]; then
              exit 0
            fi

            sudo -u builder bash -c "
              cd ~
              git clone https://aur.archlinux.org/yay.git
              cd yay && makepkg -si --noconfirm
              yay -S --noconfirm --needed ronn fmt ayugram-desktop
            "

            mkdir -p /share/pkg
            cp /home/builder/.cache/yay/ayugram-desktop/*.pkg.tar.* /share/pkg/
            pacman -Scc --noconfirm
          '

      - name: Load version info
        run: |
          source versioninfo
          echo "AUR_VERSION=$AUR_VERSION" >> $GITHUB_ENV
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Upload to releases
        uses: softprops/action-gh-release@v2.3.4
        with:
          files: pkg/*.pkg.tar.*
          tag_name: v${{ env.AUR_VERSION }}
          name: ayugram-desktop ${{ env.AUR_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup old releases
        if: ${{ always() }}
        run: |
          GH_REPO="${{ github.repository }}"
          TOKEN="${{ secrets.GITHUB_TOKEN }}"

          releases=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$GH_REPO/releases?per_page=100" \
            | jq -r '.[].tag_name')

          count=0
          for tag in $releases; do
            count=$((count + 1))
            if [ $count -le 3 ]; then
              echo "Keeping $tag"
              continue
            fi
            release_id=$(curl -s -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$GH_REPO/releases/tags/$tag" | jq -r '.id')

            if [ "$release_id" != "null" ]; then
              curl -s -X DELETE -H "Authorization: token $TOKEN" \
                "https://api.github.com/repos/$GH_REPO/releases/$release_id"
            fi
            curl -s -X DELETE -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$GH_REPO/git/refs/tags/$tag" || true
          done
